import { useEffect, useRef, useState } from 'react'
import { motion, useInView } from 'framer-motion'
import { ArrowRight, BarChart3, CalendarClock, ChartNoAxesCombined, CheckCircle2, ChevronDown, CirclePlay, CloudCog, FileBarChart, Map, MapPin, MonitorSmartphone, MousePointerClick, QrCode, Route, Send, ShieldCheck, Smartphone, Sparkles, UploadCloud, Video } from 'lucide-react'
import { launchMetrics } from '@/lib/site-data'

const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } }

function CountUp({ value }: { value: number }) {
  const node = useRef<HTMLSpanElement>(null)
  const visible = useInView(node, { once: true, margin: '-60px' })
  const [count, setCount] = useState(0)
  useEffect(() => { if (!visible) return; let start = 0; const duration = 900; const tick = (time: number) => { if (!start) start = time; const progress = Math.min((time - start) / duration, 1); setCount(Math.round(progress * value)); if (progress < 1) requestAnimationFrame(tick) }; requestAnimationFrame(tick) }, [visible, value])
  return <span ref={node}>{count}</span>
}

export function TrustSection() { return <section aria-label="AdVault at a glance" className="relative overflow-hidden bg-[#07182d] px-5 py-16 text-white sm:px-8 lg:py-20"><div className="trust-glow" /><div className="relative mx-auto max-w-7xl"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: .3 }} variants={reveal} className="max-w-xl"><p className="section-kicker text-orange-300">Launching from Lahore</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.045em] sm:text-4xl">Building the future of attention, one ride at a time.</h2></motion.div><div className="mt-11 grid grid-cols-2 divide-x divide-y divide-white/10 border border-white/10 sm:grid-cols-5 sm:divide-y-0">{launchMetrics.map((metric, i) => <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={reveal} transition={{ delay: i * .07 }} key={metric.label} className="p-5 text-center sm:p-6"><div className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">{typeof metric.value === 'number' ? <CountUp value={metric.value} /> : metric.value}</div><p className="mt-2 text-xs font-medium uppercase tracking-[.12em] text-slate-400">{metric.label}</p></motion.div>)}</div></div></section> }

const capabilities = [['Geofencing', 'Show the right campaign only inside the zones that matter.', MapPin], ['Heatmaps', 'Turn movement into clear, decision-ready audience intelligence.', Map], ['Campaign Analytics', 'Measure plays, impressions and performance as campaigns run.', ChartNoAxesCombined], ['Video Advertising', 'Command attention with rich, motion-first creative on every ride.', Video], ['QR Code Campaigns', 'Bridge the real world and digital action with scannable campaigns.', QrCode], ['High Passenger Attention', 'Reach a seated, engaged audience during meaningful ride time.', MousePointerClick], ['Location Based Advertising', 'Make every message more relevant to where passengers are.', Route], ['Cloud Dashboard', 'Manage campaigns, inventory and performance from one place.', CloudCog], ['Remote Content Updates', 'Update approved creative across the fleet without friction.', UploadCloud], ['Performance Reports', 'Give your team reports that make campaign outcomes clear.', FileBarChart], ['Smart Scheduling', 'Set timing, duration and priority with complete control.', CalendarClock], ['Zone Based Ads', 'Deploy tailored messages for the neighborhoods you choose.', Sparkles], ['Default Ads Outside Zones', 'Keep every screen valuable beyond targeted campaign boundaries.', ShieldCheck]] as const

export function WhyAdVault() { return <section id="features" className="bg-[#fbfcfd] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: .25 }} transition={{ staggerChildren: .1 }} className="max-w-2xl"><motion.p variants={reveal} className="section-kicker">Why AdVault</motion.p><motion.h2 variants={reveal} className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[#07182d] sm:text-5xl">More than screens. <span className="text-[#ff6b35]">A DOOH technology platform.</span></motion.h2><motion.p variants={reveal} className="mt-5 text-lg leading-8 text-slate-600">AdVault combines connected devices, location intelligence and cloud analytics to make every in-cab campaign precise, measurable and easy to manage.</motion.p></motion.div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{capabilities.map(([title, description, Icon], index) => <motion.article key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ delay: (index % 4) * .06 }} whileHover={{ y: -6 }} className="feature-card group"><div className="feature-icon"><Icon size={21} strokeWidth={1.8} /></div><h3 className="mt-5 text-base font-semibold text-[#0a1d35]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[#ff6b35] opacity-0 transition group-hover:opacity-100">Explore capability <ArrowRight size={13} /></span></motion.article>)}</div></div></section> }

const journey = [['Book a conversation', 'Business contacts AdVault to book a demo or speak with sales.', Send], ['Share your creative', 'Advertiser sends video or image creative along with campaign requirements.', UploadCloud], ['Review & approve', 'Our team reviews, approves and uploads creative for quality and compatibility.', CheckCircle2], ['Configure with intelligence', 'Set geofencing, zones, schedule, duration and priority for the campaign.', CalendarClock], ['Deliver to the fleet', 'Approved advertisements are automatically delivered to vehicle screens.', Smartphone], ['Capture passenger attention', 'Passengers view engaging, contextual advertisements during their rides.', CirclePlay], ['See every outcome', 'Advertisers receive real-time analytics and reports in the AdVault Dashboard.', BarChart3]] as const

export function HowItWorks() { return <section id="platform" className="relative overflow-hidden bg-white px-5 py-20 sm:px-8 lg:py-28"><div className="process-glow" /><div className="relative mx-auto max-w-7xl"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: .3 }} variants={reveal} className="mx-auto max-w-2xl text-center"><p className="section-kicker">How it works</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[#07182d] sm:text-5xl">From creative to measurable impact.</h2><p className="mt-5 text-lg leading-8 text-slate-600">A guided campaign workflow, powered by location-aware delivery and real-time reporting.</p></motion.div><div className="timeline mt-14 lg:mt-20">{journey.map(([title, description, Icon], index) => <motion.article key={title} initial={{ opacity: 0, x: index % 2 ? 28 : -28 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .45 }} className={`timeline-row ${index % 2 ? 'timeline-right' : ''}`}><div className="timeline-step">{String(index + 1).padStart(2, '0')}</div><motion.div whileHover={{ y: -4 }} className="timeline-card"><div className="timeline-icon"><Icon size={22} /></div><div><p className="text-xs font-bold uppercase tracking-[.13em] text-[#ff6b35]">Step {index + 1}</p><h3 className="mt-1 text-lg font-semibold text-[#0a1d35]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div></motion.div></motion.article>)}</div></div></section> }

const analytics = [
  ['Performance Overview', 'See reach, plays and campaign pace at a glance.', BarChart3],
  ['Heatmaps', 'Understand where passenger attention is building.', Map],
  ['Zone Analytics', 'Compare performance across your chosen locations.', MapPin],
  ['Plays by Hour', 'Find the moments your creative works hardest.', CalendarClock],
  ['Campaign Analytics', 'Track every campaign from launch through reporting.', ChartNoAxesCombined],
  ['Device Monitoring', 'Keep an eye on the health of your active fleet.', MonitorSmartphone],
  ['Recent Activity', 'Review live delivery events as they happen.', FileBarChart],
  ['Brands & Campaigns', 'Manage creative, brands and campaign inventory in one place.', Sparkles],
] as const

function AnalyticsScreen({ index }: { index: number }) {
  return <div className="analytics-screen"><div className="analytics-side"><b>A</b><i /><i /><i /></div><div className="analytics-canvas"><div className="analytics-head"><span /><span /><span /></div><div className="analytics-kpis"><i /><i /><i /></div>{index % 3 === 1 ? <div className="analytics-heat"><b /><b /><b /><b /></div> : index % 3 === 2 ? <div className="analytics-bars"><i /><i /><i /><i /><i /><i /><i /></div> : <div className="analytics-graph"><svg viewBox="0 0 240 72" preserveAspectRatio="none"><path d="M0 61 C22 53 29 39 48 46 S73 62 92 35 S130 51 148 29 S181 40 196 19 S221 30 240 7" fill="none" stroke="#ff6b35" strokeWidth="3" /><path d="M0 61 C22 53 29 39 48 46 S73 62 92 35 S130 51 148 29 S181 40 196 19 S221 30 240 7 V72 H0Z" fill="url(#miniGradient)" /></svg></div>}<div className="analytics-lines"><i /><i /><i /></div></div></div>
}

export function AnalyticsShowcase() { return <section id="analytics" className="relative overflow-hidden bg-[#f6fafc] px-5 py-20 sm:px-8 lg:py-28"><div className="analytics-glow" /><div className="relative mx-auto max-w-7xl"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: .25 }} variants={reveal} className="mx-auto max-w-2xl text-center"><p className="section-kicker">Command center</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[#07182d] sm:text-5xl">Turn every ride into <span className="text-[#ff6b35]">clear insight.</span></h2><p className="mt-5 text-lg leading-8 text-slate-600">A live, privacy-conscious dashboard built to make campaign performance easy to understand and act on.</p></motion.div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{analytics.map(([title, text, Icon], index) => <motion.article key={title} initial={{ opacity: 0, y: 26 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ delay: (index % 4) * .07 }} whileHover={{ y: -7 }} className="analytics-card"><div className="analytics-laptop"><AnalyticsScreen index={index} /><div className="analytics-base" /></div><div className="mt-5 flex items-start gap-3"><span className="analytics-icon"><Icon size={18} /></span><div><h3 className="text-sm font-semibold text-[#0a1d35]">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div></motion.article>)}</div><p className="mt-7 text-center text-xs text-slate-400">Dashboard previews use blurred placeholder data for illustration.</p></div></section> }

const cities = ['Karachi', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Quetta']
export function Coverage() { const [city, setCity] = useState('Lahore'); return <section id="coverage" className="bg-white px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.84fr_1.16fr]"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} transition={{ staggerChildren: .1 }}><motion.p variants={reveal} className="section-kicker">Coverage</motion.p><motion.h2 variants={reveal} className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[#07182d] sm:text-5xl">Starting in Lahore.<br /><span className="text-[#ff6b35]">Built to move further.</span></motion.h2><motion.p variants={reveal} className="mt-5 max-w-lg text-lg leading-8 text-slate-600">AdVault is live in Lahore today, with a growing roadmap across Pakistan's most dynamic cities.</motion.p><div className="mt-8"><button onClick={() => setCity('Lahore')} className={`city-pill ${city === 'Lahore' ? 'active' : ''}`}><span /> Lahore <small>Live now</small></button><p className="mt-6 text-xs font-bold uppercase tracking-[.14em] text-slate-400">Expanding soon</p><div className="mt-3 flex flex-wrap gap-2">{cities.map(name => <button key={name} onClick={() => setCity(name)} className={`city-pill ${city === name ? 'selected' : ''}`}>{name}</button>)}</div></div></motion.div><motion.div initial={{ opacity: 0, scale: .94 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} className="coverage-map"><div className="pakistan-shape" /><div className="map-dot lahore" onClick={() => setCity('Lahore')} /><div className="map-dot karachi" onClick={() => setCity('Karachi')} /><div className="map-dot islamabad" onClick={() => setCity('Islamabad')} /><div className="coverage-label">{city === 'Lahore' ? <><b>Lahore</b><span>Live coverage</span></> : <><b>{city}</b><span>Expanding soon</span></>}</div><div className="map-key"><i /> Live now <i className="soon" /> Expanding soon</div></motion.div></div></section> }

const industries = ['Restaurants', 'Fast Food', 'Universities', 'Hospitals', 'Real Estate', 'Banks', 'Insurance', 'Retail', 'Fashion', 'Electronics', 'Shopping Malls', 'Events', 'Automotive', 'Travel', 'Education', 'Healthcare']
export function Industries() { return <section id="industries" className="bg-[#07182d] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="section-kicker text-orange-300">Made for every category</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Reach people when your message matters most.</h2><p className="mt-5 text-lg leading-8 text-slate-400">From daily essentials to major life decisions, in-cab moments make space for meaningful brand discovery.</p></div><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{industries.map((industry, index) => <motion.div key={industry} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (index % 4) * .05 }} className="industry-card"><span>{String(index + 1).padStart(2, '0')}</span><b>{industry}</b><ArrowRight size={15} /></motion.div>)}</div></div></section> }

const comparison = [['Audience Attention', 'Competing for attention outdoors', 'A captive, seated audience'], ['Targeting', 'Broad area targeting', 'Precise zones and neighborhoods'], ['Analytics', 'Estimated visibility', 'Live campaign intelligence'], ['Video', 'Static only', 'Rich video creative'], ['Scheduling', 'Fixed placement periods', 'Flexible daypart scheduling'], ['Location Based', 'Single physical location', 'Contextual, location-aware delivery'], ['Performance Tracking', 'Limited post-campaign data', 'Plays, reach and performance reports'], ['Campaign Updates', 'Manual replacement required', 'Remote content updates'], ['ROI', 'Harder to attribute', 'Measured and optimized over time']]
export function Comparison() { return <section className="bg-[#fff8f5] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="section-kicker">Why in-cab advertising</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[#07182d] sm:text-5xl">Built for more than visibility.</h2><p className="mt-5 text-lg leading-8 text-slate-600">A smarter channel for brands that want context, control and clarity.</p></div><div className="comparison-table mt-12"><div className="comparison-row comparison-heading"><b>What matters</b><b>Traditional Billboard</b><b>AdVault</b></div>{comparison.map(([feature, old, vault]) => <motion.div initial={{ opacity: 0, x: -12 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} key={feature} className="comparison-row"><b>{feature}</b><span>{old}</span><strong>{vault}</strong></motion.div>)}</div></div></section> }

const faqs = [
  ['How many vehicles are in the AdVault network?', 'Our Lahore network is expanding in phases. Contact us for current live inventory and planned vehicle availability for your campaign dates.'],
  ['Can I upload video advertisements?', 'Yes. AdVault supports approved motion-first video creative, alongside static and QR-enabled formats.'],
  ['Can campaigns run city-wide?', 'Absolutely. You can run across the active Lahore fleet or focus delivery in selected areas.'],
  ['How do I receive analytics?', 'Your team receives dashboard access and scheduled performance reporting with campaign plays, delivery and location insight.'],
  ['Can I schedule campaigns?', 'Yes. Set campaign dates, time windows, duration and priority to match your media plan.'],
  ['How does geofencing work?', 'We define virtual boundaries around the places that matter to your campaign, then deliver eligible creative within those zones.'],
  ['What are default advertisements?', 'Default ads keep screens active outside a campaign’s chosen zone or schedule, based on the campaign rules you approve.'],
  ['How often are reports updated?', 'Dashboard delivery data is updated continuously, while formal reports can be aligned to your preferred reporting cadence.'],
  ['What creative formats do you accept?', 'We accept approved video and static screen creative. Our team will share the latest specifications before launch.'],
  ['Can I change creative after a campaign starts?', 'Yes. Approved creative can be updated remotely, so campaigns stay relevant without physical screen servicing.'],
  ['How long does campaign setup take?', 'Timing depends on creative readiness, approvals and targeting complexity. We’ll confirm a clear launch timeline during planning.'],
  ['Can I include a QR code?', 'Yes. QR-enabled creative can connect passengers to landing pages, offers, apps and other digital experiences.'],
  ['Is passenger data collected?', 'AdVault is designed around campaign-level, privacy-conscious delivery insight rather than identifying individual passengers.'],
  ['Can you help with campaign planning?', 'Yes. Our team can help shape zones, scheduling, creative requirements and the reporting plan around your objective.'],
]
export function FAQ() { const [open, setOpen] = useState<number | null>(0); return <section id="faq" className="bg-white px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="section-kicker">FAQ</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[#07182d] sm:text-5xl">Questions, answered.</h2><p className="mt-5 max-w-sm text-lg leading-8 text-slate-600">If you have a campaign question that is not here, our team is ready to help.</p></div><div className="faq-list">{faqs.map(([question, answer], index) => <article key={question} className={`faq-item ${open === index ? 'open' : ''}`}><button onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}><span>{question}</span><ChevronDown size={19} /></button><motion.div initial={false} animate={{ height: open === index ? 'auto' : 0, opacity: open === index ? 1 : 0 }} className="faq-answer"><p>{answer}</p></motion.div></article>)}</div></div></section> }
